/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../src/app/login-select-branch';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/change_detection/change_detection_util';
export class Wrapper_SelectBranch {
  /*private*/ _eventHandler:Function;
  context:import0.SelectBranch;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.SelectBranch();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_SelectBranch_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_SelectBranch_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.SelectBranch>;
  _SelectBranch_0_3:Wrapper_SelectBranch;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SelectBranch_Host0,renderType_SelectBranch_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'select-branch',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_SelectBranch0(this.viewUtils,this,0,this._el_0);
    this._SelectBranch_0_3 = new Wrapper_SelectBranch();
    this.compView_0.create(this._SelectBranch_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._SelectBranch_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SelectBranch) && (0 === requestNodeIndex))) { return this._SelectBranch_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SelectBranch_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SelectBranchNgFactory:import7.ComponentFactory<import0.SelectBranch> = new import7.ComponentFactory<import0.SelectBranch>('select-branch',View_SelectBranch_Host0,import0.SelectBranch);
const styles_SelectBranch:any[] = ['.to-left[_ngcontent-%COMP%] { float: left; }\n  .to-right[_ngcontent-%COMP%] { float: right; }'];
var renderType_SelectBranch:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_SelectBranch,{});
export class View_SelectBranch0 extends import1.AppView<import0.SelectBranch> {
  _text_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _el_105:any;
  _text_106:any;
  _text_107:any;
  _el_108:any;
  _text_109:any;
  _el_110:any;
  _text_111:any;
  _text_112:any;
  _text_113:any;
  _el_114:any;
  _text_115:any;
  _el_116:any;
  _text_117:any;
  _el_118:any;
  _text_119:any;
  _text_120:any;
  _el_121:any;
  _text_122:any;
  _el_123:any;
  _text_124:any;
  _text_125:any;
  _text_126:any;
  _el_127:any;
  _text_128:any;
  _el_129:any;
  _text_130:any;
  _el_131:any;
  _text_132:any;
  _text_133:any;
  _el_134:any;
  _text_135:any;
  _el_136:any;
  _text_137:any;
  _text_138:any;
  _text_139:any;
  _el_140:any;
  _text_141:any;
  _el_142:any;
  _text_143:any;
  _el_144:any;
  _text_145:any;
  _text_146:any;
  _el_147:any;
  _text_148:any;
  _el_149:any;
  _text_150:any;
  _text_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _el_155:any;
  _text_156:any;
  _el_157:any;
  _text_158:any;
  _text_159:any;
  _el_160:any;
  _text_161:any;
  _el_162:any;
  _text_163:any;
  _text_164:any;
  _text_165:any;
  _el_166:any;
  _text_167:any;
  _el_168:any;
  _text_169:any;
  _el_170:any;
  _text_171:any;
  _text_172:any;
  _el_173:any;
  _text_174:any;
  _el_175:any;
  _text_176:any;
  _text_177:any;
  _text_178:any;
  _el_179:any;
  _text_180:any;
  _el_181:any;
  _text_182:any;
  _el_183:any;
  _text_184:any;
  _text_185:any;
  _el_186:any;
  _text_187:any;
  _el_188:any;
  _text_189:any;
  _text_190:any;
  _text_191:any;
  _text_192:any;
  _el_193:any;
  _text_194:any;
  _el_195:any;
  _text_196:any;
  _el_197:any;
  _text_198:any;
  _el_199:any;
  _text_200:any;
  _el_201:any;
  _text_202:any;
  _el_203:any;
  _text_204:any;
  _text_205:any;
  _text_206:any;
  _text_207:any;
  _el_208:any;
  _el_209:any;
  _text_210:any;
  _text_211:any;
  _el_212:any;
  _el_213:any;
  _text_214:any;
  _text_215:any;
  _el_216:any;
  _el_217:any;
  _text_218:any;
  _text_219:any;
  _el_220:any;
  _el_221:any;
  _text_222:any;
  _text_223:any;
  _el_224:any;
  _el_225:any;
  _text_226:any;
  _text_227:any;
  _el_228:any;
  _text_229:any;
  _el_230:any;
  _text_231:any;
  _el_232:any;
  _text_233:any;
  _text_234:any;
  _text_235:any;
  _text_236:any;
  _text_237:any;
  _text_238:any;
  _text_239:any;
  _el_240:any;
  _text_241:any;
  _el_242:any;
  _text_243:any;
  _el_244:any;
  _text_245:any;
  _text_246:any;
  _text_247:any;
  _text_248:any;
  _text_249:any;
  _text_250:any;
  _text_251:any;
  /*private*/ _expr_252:any;
  /*private*/ _expr_253:any;
  /*private*/ _expr_254:any;
  /*private*/ _expr_255:any;
  /*private*/ _expr_256:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SelectBranch0,renderType_SelectBranch,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_252 = import8.UNINITIALIZED;
    this._expr_253 = import8.UNINITIALIZED;
    this._expr_254 = import8.UNINITIALIZED;
    this._expr_255 = import8.UNINITIALIZED;
    this._expr_256 = import8.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-8 col-md-6 col-md-offset-3 col-sm-offset-2'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','well well-md'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'h1',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_8,'h1',new import3.InlineArray2(2,'class','text-center text-info'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'span',new import3.InlineArray2(2,'class','fa-stack fa-lg'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'i',new import3.InlineArray2(2,'class','fa fa-circle fa-stack-2x'),(null as any));
    this._text_18 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_15,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-stack-1x fa-inverse'),(null as any));
    this._text_20 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_8,'\n\n                ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_8,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'',(null as any));
    this._text_25 = this.renderer.createText(this._el_8,'\n\n                ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','list-group'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                        ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_31 = this.renderer.createText(this._el_28,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_28,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'(B3)',(null as any));
    this._text_34 = this.renderer.createText(this._el_28,'\n                        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_28,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                          ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-trash text-danger fa-lg'),(null as any));
    this._text_38 = this.renderer.createText(this._el_35,'\n                          ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_35,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_40 = this.renderer.createText(this._el_35,'  \n                        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_28,'\n                    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._text_43 = this.renderer.createText(this._el_8,'\n\n                ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_8,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'',(null as any));
    this._text_46 = this.renderer.createText(this._el_8,'\n\n                \n                ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','input-group'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'input',new import3.InlineArray4(4,'class','form-control','type','text'),(null as any));
    this._text_50 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_47,'span',new import3.InlineArray2(2,'class','input-group-addon'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n                        ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_51,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-search'),(null as any));
    this._text_54 = this.renderer.createText(this._el_51,'\n                    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_47,'\n                ',(null as any));
    this._text_56 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_8,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'',(null as any));
    this._text_59 = this.renderer.createText(this._el_8,'\n\n                ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','list-group'),(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'\n                \n                    ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_60,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'\n                        ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_62,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_65 = this.renderer.createText(this._el_62,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_62,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'(B3)',(null as any));
    this._text_68 = this.renderer.createText(this._el_62,'\n                        ',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_62,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'\n                          ',(null as any));
    this._el_71 = import3.createRenderElement(this.renderer,this._el_69,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_72 = this.renderer.createText(this._el_69,'  \n                        ',(null as any));
    this._text_73 = this.renderer.createText(this._el_62,'\n                    ',(null as any));
    this._text_74 = this.renderer.createText(this._el_60,'\n                    ',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_60,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'\n                        ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_75,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_78 = this.renderer.createText(this._el_75,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_75,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'(B3)',(null as any));
    this._text_81 = this.renderer.createText(this._el_75,'\n                        ',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_75,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'\n                          ',(null as any));
    this._el_84 = import3.createRenderElement(this.renderer,this._el_82,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_85 = this.renderer.createText(this._el_82,'  \n                        ',(null as any));
    this._text_86 = this.renderer.createText(this._el_75,'\n                    ',(null as any));
    this._text_87 = this.renderer.createText(this._el_60,'\n                    ',(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_60,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_89 = this.renderer.createText(this._el_88,'\n                        ',(null as any));
    this._el_90 = import3.createRenderElement(this.renderer,this._el_88,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_91 = this.renderer.createText(this._el_88,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_88,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'(B3)',(null as any));
    this._text_94 = this.renderer.createText(this._el_88,'\n                        ',(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,this._el_88,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'\n                          ',(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_95,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_98 = this.renderer.createText(this._el_95,'  \n                        ',(null as any));
    this._text_99 = this.renderer.createText(this._el_88,'\n                    ',(null as any));
    this._text_100 = this.renderer.createText(this._el_60,'\n                    ',(null as any));
    this._el_101 = import3.createRenderElement(this.renderer,this._el_60,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'\n                        ',(null as any));
    this._el_103 = import3.createRenderElement(this.renderer,this._el_101,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_104 = this.renderer.createText(this._el_101,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_105 = import3.createRenderElement(this.renderer,this._el_101,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_106 = this.renderer.createText(this._el_105,'(B3)',(null as any));
    this._text_107 = this.renderer.createText(this._el_101,'\n                        ',(null as any));
    this._el_108 = import3.createRenderElement(this.renderer,this._el_101,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_109 = this.renderer.createText(this._el_108,'\n                          ',(null as any));
    this._el_110 = import3.createRenderElement(this.renderer,this._el_108,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_111 = this.renderer.createText(this._el_108,'  \n                        ',(null as any));
    this._text_112 = this.renderer.createText(this._el_101,'\n                    ',(null as any));
    this._text_113 = this.renderer.createText(this._el_60,'\n                    ',(null as any));
    this._el_114 = import3.createRenderElement(this.renderer,this._el_60,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_115 = this.renderer.createText(this._el_114,'\n                        ',(null as any));
    this._el_116 = import3.createRenderElement(this.renderer,this._el_114,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_117 = this.renderer.createText(this._el_114,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_118 = import3.createRenderElement(this.renderer,this._el_114,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_119 = this.renderer.createText(this._el_118,'(B3)',(null as any));
    this._text_120 = this.renderer.createText(this._el_114,'\n                        ',(null as any));
    this._el_121 = import3.createRenderElement(this.renderer,this._el_114,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_122 = this.renderer.createText(this._el_121,'\n                          ',(null as any));
    this._el_123 = import3.createRenderElement(this.renderer,this._el_121,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_124 = this.renderer.createText(this._el_121,'  \n                        ',(null as any));
    this._text_125 = this.renderer.createText(this._el_114,'\n                    ',(null as any));
    this._text_126 = this.renderer.createText(this._el_60,'\n                    ',(null as any));
    this._el_127 = import3.createRenderElement(this.renderer,this._el_60,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_128 = this.renderer.createText(this._el_127,'\n                        ',(null as any));
    this._el_129 = import3.createRenderElement(this.renderer,this._el_127,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_130 = this.renderer.createText(this._el_127,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_131 = import3.createRenderElement(this.renderer,this._el_127,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_132 = this.renderer.createText(this._el_131,'(B3)',(null as any));
    this._text_133 = this.renderer.createText(this._el_127,'\n                        ',(null as any));
    this._el_134 = import3.createRenderElement(this.renderer,this._el_127,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_135 = this.renderer.createText(this._el_134,'\n                          ',(null as any));
    this._el_136 = import3.createRenderElement(this.renderer,this._el_134,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_137 = this.renderer.createText(this._el_134,'  \n                        ',(null as any));
    this._text_138 = this.renderer.createText(this._el_127,'\n                    ',(null as any));
    this._text_139 = this.renderer.createText(this._el_60,'\n                    ',(null as any));
    this._el_140 = import3.createRenderElement(this.renderer,this._el_60,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_141 = this.renderer.createText(this._el_140,'\n                        ',(null as any));
    this._el_142 = import3.createRenderElement(this.renderer,this._el_140,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_143 = this.renderer.createText(this._el_140,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_144 = import3.createRenderElement(this.renderer,this._el_140,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_145 = this.renderer.createText(this._el_144,'(B3)',(null as any));
    this._text_146 = this.renderer.createText(this._el_140,'\n                        ',(null as any));
    this._el_147 = import3.createRenderElement(this.renderer,this._el_140,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_148 = this.renderer.createText(this._el_147,'\n                          ',(null as any));
    this._el_149 = import3.createRenderElement(this.renderer,this._el_147,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_150 = this.renderer.createText(this._el_147,'  \n                        ',(null as any));
    this._text_151 = this.renderer.createText(this._el_140,'\n                    ',(null as any));
    this._text_152 = this.renderer.createText(this._el_60,'\n                    ',(null as any));
    this._el_153 = import3.createRenderElement(this.renderer,this._el_60,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_154 = this.renderer.createText(this._el_153,'\n                        ',(null as any));
    this._el_155 = import3.createRenderElement(this.renderer,this._el_153,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_156 = this.renderer.createText(this._el_153,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_157 = import3.createRenderElement(this.renderer,this._el_153,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_158 = this.renderer.createText(this._el_157,'(B3)',(null as any));
    this._text_159 = this.renderer.createText(this._el_153,'\n                        ',(null as any));
    this._el_160 = import3.createRenderElement(this.renderer,this._el_153,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_161 = this.renderer.createText(this._el_160,'\n                          ',(null as any));
    this._el_162 = import3.createRenderElement(this.renderer,this._el_160,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_163 = this.renderer.createText(this._el_160,'  \n                        ',(null as any));
    this._text_164 = this.renderer.createText(this._el_153,'\n                    ',(null as any));
    this._text_165 = this.renderer.createText(this._el_60,'\n                    ',(null as any));
    this._el_166 = import3.createRenderElement(this.renderer,this._el_60,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_167 = this.renderer.createText(this._el_166,'\n                        ',(null as any));
    this._el_168 = import3.createRenderElement(this.renderer,this._el_166,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_169 = this.renderer.createText(this._el_166,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_170 = import3.createRenderElement(this.renderer,this._el_166,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_171 = this.renderer.createText(this._el_170,'(B3)',(null as any));
    this._text_172 = this.renderer.createText(this._el_166,'\n                        ',(null as any));
    this._el_173 = import3.createRenderElement(this.renderer,this._el_166,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_174 = this.renderer.createText(this._el_173,'\n                          ',(null as any));
    this._el_175 = import3.createRenderElement(this.renderer,this._el_173,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_176 = this.renderer.createText(this._el_173,'  \n                        ',(null as any));
    this._text_177 = this.renderer.createText(this._el_166,'\n                    ',(null as any));
    this._text_178 = this.renderer.createText(this._el_60,'\n                    ',(null as any));
    this._el_179 = import3.createRenderElement(this.renderer,this._el_60,'a',new import3.InlineArray4(4,'class','list-group-item','href','javascript:void(0)'),(null as any));
    this._text_180 = this.renderer.createText(this._el_179,'\n                        ',(null as any));
    this._el_181 = import3.createRenderElement(this.renderer,this._el_179,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-home fa-fw'),(null as any));
    this._text_182 = this.renderer.createText(this._el_179,'\n                        1111 Budapest Üllői út 11 ',(null as any));
    this._el_183 = import3.createRenderElement(this.renderer,this._el_179,'small',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_184 = this.renderer.createText(this._el_183,'(B3)',(null as any));
    this._text_185 = this.renderer.createText(this._el_179,'\n                        ',(null as any));
    this._el_186 = import3.createRenderElement(this.renderer,this._el_179,'span',new import3.InlineArray2(2,'class','to-right'),(null as any));
    this._text_187 = this.renderer.createText(this._el_186,'\n                          ',(null as any));
    this._el_188 = import3.createRenderElement(this.renderer,this._el_186,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-chevron-right fa-lg'),(null as any));
    this._text_189 = this.renderer.createText(this._el_186,'  \n                        ',(null as any));
    this._text_190 = this.renderer.createText(this._el_179,'\n                    ',(null as any));
    this._text_191 = this.renderer.createText(this._el_60,'\n                ',(null as any));
    this._text_192 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_193 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','text-center'),(null as any));
    this._text_194 = this.renderer.createText(this._el_193,'\n                    ',(null as any));
    this._el_195 = import3.createRenderElement(this.renderer,this._el_193,'nav',new import3.InlineArray2(2,'aria-label','Page navigation'),(null as any));
    this._text_196 = this.renderer.createText(this._el_195,'\n                        ',(null as any));
    this._el_197 = import3.createRenderElement(this.renderer,this._el_195,'ul',new import3.InlineArray2(2,'class','pagination'),(null as any));
    this._text_198 = this.renderer.createText(this._el_197,'\n                            ',(null as any));
    this._el_199 = import3.createRenderElement(this.renderer,this._el_197,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_200 = this.renderer.createText(this._el_199,'\n                            ',(null as any));
    this._el_201 = import3.createRenderElement(this.renderer,this._el_199,'a',new import3.InlineArray4(4,'aria-label','Previous','href','#'),(null as any));
    this._text_202 = this.renderer.createText(this._el_201,'\n                                ',(null as any));
    this._el_203 = import3.createRenderElement(this.renderer,this._el_201,'span',new import3.InlineArray2(2,'aria-hidden','true'),(null as any));
    this._text_204 = this.renderer.createText(this._el_203,'«',(null as any));
    this._text_205 = this.renderer.createText(this._el_201,'\n                            ',(null as any));
    this._text_206 = this.renderer.createText(this._el_199,'\n                            ',(null as any));
    this._text_207 = this.renderer.createText(this._el_197,'\n                            ',(null as any));
    this._el_208 = import3.createRenderElement(this.renderer,this._el_197,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_209 = import3.createRenderElement(this.renderer,this._el_208,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_210 = this.renderer.createText(this._el_209,'1',(null as any));
    this._text_211 = this.renderer.createText(this._el_197,'\n                            ',(null as any));
    this._el_212 = import3.createRenderElement(this.renderer,this._el_197,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_213 = import3.createRenderElement(this.renderer,this._el_212,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_214 = this.renderer.createText(this._el_213,'2',(null as any));
    this._text_215 = this.renderer.createText(this._el_197,'\n                            ',(null as any));
    this._el_216 = import3.createRenderElement(this.renderer,this._el_197,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_217 = import3.createRenderElement(this.renderer,this._el_216,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_218 = this.renderer.createText(this._el_217,'3',(null as any));
    this._text_219 = this.renderer.createText(this._el_197,'\n                            ',(null as any));
    this._el_220 = import3.createRenderElement(this.renderer,this._el_197,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_221 = import3.createRenderElement(this.renderer,this._el_220,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_222 = this.renderer.createText(this._el_221,'4',(null as any));
    this._text_223 = this.renderer.createText(this._el_197,'\n                            ',(null as any));
    this._el_224 = import3.createRenderElement(this.renderer,this._el_197,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_225 = import3.createRenderElement(this.renderer,this._el_224,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_226 = this.renderer.createText(this._el_225,'5',(null as any));
    this._text_227 = this.renderer.createText(this._el_197,'\n                            ',(null as any));
    this._el_228 = import3.createRenderElement(this.renderer,this._el_197,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_229 = this.renderer.createText(this._el_228,'\n                            ',(null as any));
    this._el_230 = import3.createRenderElement(this.renderer,this._el_228,'a',new import3.InlineArray4(4,'aria-label','Next','href','#'),(null as any));
    this._text_231 = this.renderer.createText(this._el_230,'\n                                ',(null as any));
    this._el_232 = import3.createRenderElement(this.renderer,this._el_230,'span',new import3.InlineArray2(2,'aria-hidden','true'),(null as any));
    this._text_233 = this.renderer.createText(this._el_232,'»',(null as any));
    this._text_234 = this.renderer.createText(this._el_230,'\n                            ',(null as any));
    this._text_235 = this.renderer.createText(this._el_228,'\n                            ',(null as any));
    this._text_236 = this.renderer.createText(this._el_197,'\n                        ',(null as any));
    this._text_237 = this.renderer.createText(this._el_195,'\n                    ',(null as any));
    this._text_238 = this.renderer.createText(this._el_193,'\n                ',(null as any));
    this._text_239 = this.renderer.createText(this._el_8,'\n\n\n                ',(null as any));
    this._el_240 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class',''),(null as any));
    this._text_241 = this.renderer.createText(this._el_240,'\n                    ',(null as any));
    this._el_242 = import3.createRenderElement(this.renderer,this._el_240,'button',new import3.InlineArray2(2,'class','btn btn-md btn-default btn-block'),(null as any));
    this._text_243 = this.renderer.createText(this._el_242,'\n                        ',(null as any));
    this._el_244 = import3.createRenderElement(this.renderer,this._el_242,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-sign-out'),(null as any));
    this._text_245 = this.renderer.createText(this._el_242,'',(null as any));
    this._text_246 = this.renderer.createText(this._el_240,'\n                ',(null as any));
    this._text_247 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._text_248 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_249 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_250 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_251 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._el_105,
      this._text_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._el_110,
      this._text_111,
      this._text_112,
      this._text_113,
      this._el_114,
      this._text_115,
      this._el_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._text_120,
      this._el_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._text_125,
      this._text_126,
      this._el_127,
      this._text_128,
      this._el_129,
      this._text_130,
      this._el_131,
      this._text_132,
      this._text_133,
      this._el_134,
      this._text_135,
      this._el_136,
      this._text_137,
      this._text_138,
      this._text_139,
      this._el_140,
      this._text_141,
      this._el_142,
      this._text_143,
      this._el_144,
      this._text_145,
      this._text_146,
      this._el_147,
      this._text_148,
      this._el_149,
      this._text_150,
      this._text_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._el_155,
      this._text_156,
      this._el_157,
      this._text_158,
      this._text_159,
      this._el_160,
      this._text_161,
      this._el_162,
      this._text_163,
      this._text_164,
      this._text_165,
      this._el_166,
      this._text_167,
      this._el_168,
      this._text_169,
      this._el_170,
      this._text_171,
      this._text_172,
      this._el_173,
      this._text_174,
      this._el_175,
      this._text_176,
      this._text_177,
      this._text_178,
      this._el_179,
      this._text_180,
      this._el_181,
      this._text_182,
      this._el_183,
      this._text_184,
      this._text_185,
      this._el_186,
      this._text_187,
      this._el_188,
      this._text_189,
      this._text_190,
      this._text_191,
      this._text_192,
      this._el_193,
      this._text_194,
      this._el_195,
      this._text_196,
      this._el_197,
      this._text_198,
      this._el_199,
      this._text_200,
      this._el_201,
      this._text_202,
      this._el_203,
      this._text_204,
      this._text_205,
      this._text_206,
      this._text_207,
      this._el_208,
      this._el_209,
      this._text_210,
      this._text_211,
      this._el_212,
      this._el_213,
      this._text_214,
      this._text_215,
      this._el_216,
      this._el_217,
      this._text_218,
      this._text_219,
      this._el_220,
      this._el_221,
      this._text_222,
      this._text_223,
      this._el_224,
      this._el_225,
      this._text_226,
      this._text_227,
      this._el_228,
      this._text_229,
      this._el_230,
      this._text_231,
      this._el_232,
      this._text_233,
      this._text_234,
      this._text_235,
      this._text_236,
      this._text_237,
      this._text_238,
      this._text_239,
      this._el_240,
      this._text_241,
      this._el_242,
      this._text_243,
      this._el_244,
      this._text_245,
      this._text_246,
      this._text_247,
      this._text_248,
      this._text_249,
      this._text_250,
      this._text_251
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_252:any = import3.inlineInterpolate(1,'','login.selectBranch','');
    if (import3.checkBinding(throwOnChange,this._expr_252,currVal_252)) {
      this.renderer.setText(this._text_11,currVal_252);
      this._expr_252 = currVal_252;
    }
    const currVal_253:any = import3.inlineInterpolate(1,'','login.lastSelected','');
    if (import3.checkBinding(throwOnChange,this._expr_253,currVal_253)) {
      this.renderer.setText(this._text_24,currVal_253);
      this._expr_253 = currVal_253;
    }
    const currVal_254:any = import3.inlineInterpolate(1,'','login.allBranches','');
    if (import3.checkBinding(throwOnChange,this._expr_254,currVal_254)) {
      this.renderer.setText(this._text_45,currVal_254);
      this._expr_254 = currVal_254;
    }
    const currVal_255:any = import3.inlineInterpolate(1,'\n                    ','login.searchInBranches','\n                ');
    if (import3.checkBinding(throwOnChange,this._expr_255,currVal_255)) {
      this.renderer.setText(this._text_58,currVal_255);
      this._expr_255 = currVal_255;
    }
    const currVal_256:any = import3.inlineInterpolate(1,'\n                        ','login.exit','\n                    ');
    if (import3.checkBinding(throwOnChange,this._expr_256,currVal_256)) {
      this.renderer.setText(this._text_245,currVal_256);
      this._expr_256 = currVal_256;
    }
  }
}